### ISSUE TITLE
Browserpass on Firefox is not showing the pinentry

### ISSUE THREAD

**Issue by suroa** [browserpass/browserpass#330] opened 2019-03-28 03:10 UTC
### General information
* Operating system + version: Arch Linux (up to date)
* Browser + version: Firefox 66.0.1 (64-bit) 
* Information about the host app:
  * How did you install it?
    * Installed via a package manager.
  * If installed an official release, put a version: 2.0.21
* Information about the browser extension:
  * How did you install it?
    * Installed via webstore.
  * Browserpass extension version as reported by your browser:  Browserpass 2.0.2.2
---

### Exact steps to reproduce the problem
1. Try to have browserpass autofill a login form without having already filled a pinentry recently.
2. No pinentry shows up.
3. The form ends up blank.

### What should happen?
A pinentry should show up. In my case pinentry-gnome3.
### What happened instead?
Nothing showed up and the form was not filled.

**Comment by maximbaz** [comment] 2019-03-30 00:59
Hi, please try out Browserpass v3 and let me know if the issue is still present: https://github.com/browserpass/browserpass/issues/331

This has been previously reported (https://github.com/browserpass/browserpass/issues/281), but I don't know what I can do on Browserpass side to help, the extension is not responsible for opening pinentry dialog, it's the `gpg` itself.

The only suggestion I can think of is make sure a proper pinentry application is configured in `gpg-agent.conf`, see this section of the documentation for more info: https://github.com/browserpass/browserpass-native/#hints-for-configuring-gpg

Closing as I don't really know what I can do on Browserpass side, but do let me know if you solve the issue. Good luck!

**Closed by maximbaz** 2019-03-30 00:59 UTC

**Comment by jrmaingo** [comment] 2019-03-30 02:34
I was able to solve a similar sounding issue on my laptop by pointing gpg towards the pinentry program

```
# in ~/.gnupg/gpg-agent.conf, replace '/usr/local/bin/pinentry-mac' with the path to 'pinentry-gnome3'
    pinentry-program /usr/local/bin/pinentry-mac
```
