### ISSUE TITLE
Single click login possible?

### ISSUE THREAD

**Issue by pimlie** [browserpass/browserpass#318] opened 2019-02-12 10:08 UTC
I have read the docs but unfortunately I couldnt find this information: is it possible to have a single click solution with browserpass? Eg currently I have to click twice, first the extension icon and then the saved password (thanks to auto submit, otherwise it would have been 3 clicks).

Although I understand there might be security considerations, it would be very user-friendly if for trusted/known urls (like github) I can just login with one click.

**Comment by maximbaz** [comment] 2019-02-12 10:45
Hey, thanks for the idea, it's not currently possible, we have a feature request for something similar: #277 

I'm not sure I like the idea about making click on the button do a form fill instead of opening popup, because then it won't be possible to access popup in those cases when you actually need it (i.e. if you want to select a second github account). Having two shortcuts sounds like a good balance between security and user-friendliness, you always have a choice what you want to do.

Closing this as duplicate of #277, we'll reconsider everything once we get to implement that feature.

**Closed by maximbaz** 2019-02-12 10:45 UTC
