### ISSUE TITLE
Timeout while entering passphrase

### ISSUE THREAD

**Issue by jplitza** [browserpass/browserpass#20] opened 2016-12-22 19:02 UTC
Apparently, both Firefox and Chrome/Chromium have a timeout while waiting for the response of the native app. Entering your GPG passphrase during that timeout is almost impossible if you have a reasonably long one.

I haven't found any way of working around that yet (but I have no clue about web extensions, so that doesn't necessarily mean anything).

**Comment by eterps** [comment] 2017-04-25 20:44
I also have the problem that it not possible to enter the passphrase fast enough.

I don't have much experience with browser extensions either, but it seems that browserpass needs to use `chrome.runtime.connectNative` to avoid timeouts (for Chrome/Chromium at least), i.e.:

> If using chrome.runtime.sendNativeMessage, the native app will be around right after receiving and before sending the message. Since reception of the message is asynchronous, you cannot assume that the app is still alive when the callback of sendNativeMessage is called.
>
> If you want to ensure that the native app stays around longer, use chrome.runtime.connectNative. This creates a port, and the native app will be alive until it exits or until the extension calls disconnect() on the port. If your app unexpectedly terminates early, then you have most likely made an error in the implementation of the native messaging protocol.
>
> For the exact format of the native messaging protocol, take a look at the documentation: https://developer.chrome.com/extensions/nativeMessaging#native-messaging-host-protocol

Source: http://stackoverflow.com/a/31517513/183605

**Comment by maximbaz** [comment] 2018-10-14 21:49
I cannot reproduce this, I let GPG passphrase prompt hang for 5 minutes, then enter my passphrase, and browserpass successfully proceeds with filling in the form.

Also, we decided against using persistent connection to the host app via `connectNative`, we want to keep browserpass stateless.

If you still experience this issue, try to investigate the issue a bit more, maybe the problem is not with timeouts. If it is, one workaround I could think of is to configure `default-cache-ttl` and `maximum-cache-ttl` to larger values in `gpg-agent.conf` and unlock your GPG in terminal prior using browserpass.

Closing because we are not planning to switch to using `connectNative`, but if anyone has new findings or workarounds, please share.

**Closed by maximbaz** 2018-10-14 21:49 UTC
Labels: enhancement

**Comment by maximbaz** [comment] 2018-10-14 21:51
Just a random idea, maybe what you meant is that GPG prompt itself disappears before you manage to enter the passphrase? If this is the case, it's not a browserpass issue, simply set `pinentry-timeout 86400` in your `gpg-agent.conf`.
