### ISSUE TITLE
Submit button or password field is not autofocused in Firefox after password is filled in

### ISSUE THREAD

**Issue by cptMikky** [browserpass/browserpass#200] opened 2017-12-29 11:53 UTC
When a password is selected and form is filled, the password field should be focused so that the pre-filled form can be submitted by simply pressing ENTER. 

Currently no element on the site is focused so after filling the form one must pull one's hands away from the keyboard and reach for the mouse, which is rather inconvenient.

**Comment by maximbaz** [comment] 2017-12-29 12:21
This is already implemented, but might be broken on a particular website - please share the link where it doesn't work and I'll have a look if it is possible to fix (some websites have an awful markup).

**Comment by cptMikky** [comment] 2017-12-29 12:27
As far as I can tell it does not work on any website.  I mostly use this on intranet systems so I can't give you specific sites but if you have access to, say, OpenNebula, Jenkins, OwnCloud or RainLoop instance, these are all the type of sites where I can confirm the focus is not working. Another might be Aliexpress. It doesn't even work here on GitHub.

Using Firefox 57.0.2 on Arch Linux.

**Comment by maximbaz** [comment] 2017-12-29 12:28
Could you fill out the issue template, to make sure you are on the latest version?

https://github.com/dannyvankooten/browserpass/blob/master/ISSUE_TEMPLATE.md

**Comment by cptMikky** [comment] 2017-12-29 12:58
of course, sorry, didn't expect a feature req. become a bug report :)

General information
    Operating system + version: Arch Linux, N/A 
    Browser + version: FF 57.0.2
    If installed an official release, put a release version: 2.0.9
    Browserpass extension version as reported by your browser: 2.0.9

Exact steps to reproduce the problem

ctrl+shift+L, select entry, hit enter

What should happen?

A form field (preferably password) should be focused.

What happened instead?

a form is filled but no element is focused

**Comment by maximbaz** [comment] 2017-12-29 13:13
Huh, it's a Firefox issue, I do reproduce it on github.com. Thanks for the report 🙂

As a temporary workaround, you can enable "Auto-Submit login forms" in the addon options, surprisingly this feature works even thought it is implemented in the same manner as autofocus feature.

**Comment by maximbaz** [comment] 2018-01-01 15:30
Had a closer look, apparently after the extension popup is closed, Firefox contrary to Chromium does not return the focus to the website window, so we cannot programmatically put focus to any element as the entire window is not focused.

I've seen some weirdness in Firefox's focusing behavior before, and someone came up with workarounds that seem to work fine, like the one below:

https://github.com/dannyvankooten/browserpass/blob/684e4eadc57d5df74d4488775c6fdf22634a1745/chrome/script.browserify.js#L247-L252

But I can't think of any workaround for this bug. I'll mark the issue as `help wanted` in case someone thinks of a workaround, but I'm afraid there's nothing we can do until the behavior is fixed in Firefox itself.

**Comment by cptMikky** [comment] 2018-01-01 21:22
Perhaps filling an upstream bug? I'm not sure I understand the mechanics of this misbehaviour well enough to fill one but maybe someone else does?

**Comment by maximbaz** [comment] 2018-01-01 22:38
That would certainly be useful, I use this feature daily in Chromium and I definitely think it's an important one to have. 

I don't think I understand the full mechanics too in order to submit a bug report, and I'm not even entirely sure that this is a bug in Firefox or just me not knowing how to get the focus to the main page. 

I think we need someone knowledgeable to investigate this a bit further, and when reporting an upstream bug maybe even create a simplified (and yet fully working) example to help the developers reproduce and understand the issue. 

If someone does create an upstream bug, please post the link here for others to follow.

**Comment by madduck** [comment] 2018-02-27 21:00
Yeah, this bug (not focusing the web view) is driving us Tridactyl users insane.

On the other hand, PassFF somehow manages to get around this, so maybe look at how they do it?

**Comment by maximbaz** [comment] 2018-02-27 21:12
This project is mostly community-driven, feel free to investigate and make a PR, I will gladly provide explanations of how things work in this project, as well as review & merge the PR 🙂

**Comment by maximbaz** [comment] 2018-03-22 20:24
Accidentally stumbled upon the fact that it seems PassFF [does not manage to get around this](https://github.com/passff/passff/issues/260) after all.

**Comment by maximbaz** [comment] 2018-03-22 20:32
By the way, if you trust "Auto-submit login forms" option, you can turn it on in the extension options - this works in Firefox.

**Comment by maximbaz** [comment] 2018-05-04 19:41
This is awesome news! I'll wait until 61 becomes stable and test on Linux (right now it's 59 and bug is present).

**Comment by FST777** [comment] 2018-09-21 09:57
I still seem to have this bug with Firefox 62 on Linux. After filling (and auto-submitting) a form with browserpass I need to press `Shift-Tab` (or 4 × `Tab`) to get focus back to the actual website before I can use Vimium again. The same happens when I just press `Ctrl-Shift-L` and then follow up with `Esc`.

Not that big of a deal, but a bit of a nuisance nonetheless :slightly_smiling_face:

**Comment by maximbaz** [comment] 2018-10-14 21:12
Just tried on Firefox 62 and confirm that the bug is still reproducible for me. Unfortunately I don't know what I can do about it, thus closing. If anyone has any ideas, a hint or a PR is very welcome.

**Closed by maximbaz** 2018-10-14 21:12 UTC
Labels: bug, help wanted

**Comment by apropostech** [comment] 2018-10-15 06:47
Odd. Has been working for me in Firefox Developer Edition since v. 61 on Mac (not prior though so was clearly fixed) as I pointed out above. Still working today in 63.0b13.

**Comment by FST777** [comment] 2018-10-23 15:17
Not sure if it's helpful, but Bitwarden seems to have a way of filling form data that retains focus somehow. I'm not (much of) a coder, but they seem to use a different mechanism for interacting with the page:
https://github.com/bitwarden/browser/blob/master/src/browser/browserApi.ts#L91

**Comment by maximbaz** [comment] 2018-10-23 20:55
On a first glance it looks they are using exactly the same API as we do, maybe you are in the lucky group of people who don't repro the bug, or Firefox is inconsistent in it's ability to retain focus.
